Aesthetic
gzhihongwei/bias-in-facial-recognition pull request #30
Opened 2021-07-21 21:33 UTC by rmattson1008

close #17

includes user self-identification survey

2021-07-21 22:15 UTC, gzhihongwei requested changes
Most stuff is stylistic, but I think in some cases we should make changes.

2021-07-21 22:15 UTC, gzhihongwei commented on templates/identification/bootstrap_ident.html
> +        var popup = document.getElementById("myPopup");
Please use `let` and `document.querySelecter('#myPopup')` for consistency.

2021-07-21 22:15 UTC, gzhihongwei commented on templates/identification/bootstrap_ident.html
> +      function show_popup() {
I would recommend that you first query select for `.popup`, and then add the click event listener like shown below

```javascript
const popup = document.querySelector('.popup')
const myPopup = document.querySelector('#myPopup')

popup.addEventListener('click', () => myPopup.classList.toggle('show'))
```

2021-07-21 22:15 UTC, gzhihongwei commented on templates/identification/bootstrap_ident.html
> +  <div class="popup" onclick="show_popup()"><u>Instructions</u>
Remove `onclick` after doing what's said above.

2021-07-21 22:15 UTC, gzhihongwei commented on templates/user_details/user_details1.html
> +	    <input type="text" name="email" required pattern = "[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}">><br>
Eliminate the spacing between `pattern`, the equals sign, and the string. Also, this regex might need to include more special characters (what goes in the square brackets).

2021-07-21 22:15 UTC, gzhihongwei commented on templates/verification/bootstrap_ver.html
> +      function show_popup() {
Similar comment to above.

2021-07-21 22:15 UTC, gzhihongwei commented on templates/user_details/user_details2.html
> +        <script>
Again, try to separate this into a separate file. Please use `let` if possible.

2021-07-21 22:15 UTC, gzhihongwei commented on templates/user_details/user_details2.html
> +<title>{%block title%}
I don't think there is a title block in the base html template? Maybe move this to the `head` block with just the `title` tags.

2021-07-21 22:21 UTC, gzhihongwei submitted a review, later dismissed
LGTM

2021-07-22 01:13 UTC, tiyeAKM commented on static/css/ident_style4.css
> +   animation: fadeIn 1s
";"  needed for animated styling.

2021-07-22 01:16 UTC, tiyeAKM commented on static/css/user_details2_style.css
> +    animation: fadeIn 1s
same typo, see above.

2021-07-22 01:16 UTC, tiyeAKM commented on static/css/ver_style.css
> +    animation: fadeIn 1s
see above ^

2021-07-22 01:17 UTC, tiyeAKM submitted a review, later dismissed

2021-07-22 16:04 UTC, rmattson1008 commented on templates/user_details/user_details1.html
> +	    <input type="text" name="email" required pattern = "[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}">><br>
I believe this template is out of date, still in existence just because we've been doing that with other template files in main. Could delete.

2021-07-22 16:34 UTC, gzhihongwei approved these changes
LGTM

2021-07-22 16:34 UTC, gzhihongwei approved these changes

2021-07-22 16:36 UTC, merged

2021-07-22 16:46 UTC, tiyeAKM approved these changes
ACK